name: onu-server-CI-test

on:
  pull_request:
    branches:
      - be
      - dev
jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # ✅ 전체 브랜치 및 커밋 히스토리를 가져옴

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Start MongoDB  # ✅ MongoDB 실행
        run: docker run -d -p 27017:27017 --name mongodb mongo:5.0

      - name: Start Redis  # ✅ Redis 실행
        run: docker run -d -p 6379:6379 --name redis redis:latest

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Grant execute permission for gradlew
        run: chmod +x backend/gradlew

      - name: Force clean build
        working-directory: backend
        run: ./gradlew clean assemble --refresh-dependencies  # ✅ Gradle 캐시 정리 후 전체 빌드

      - name: Run Tests
        working-directory: backend
        run: ./gradlew clean build test  # ✅ build + test 실행하여 모든 코드 포함

      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: backend/build/reports/tests/
